
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Muaz Ahmed
 */
public class SirketMuduruEkrani extends javax.swing.JFrame {

    DefaultListModel DLM = new DefaultListModel();

    /**
     * Creates new form SirketMuduruEkrani
     */
    public SirketMuduruEkrani() {
        initComponents();
        this.setLocationRelativeTo(null);
        jList1.setModel(DLM);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButtonBirimdekiBitmisGorevler = new javax.swing.JButton();
        jButtonbirimdekiBitmemisGorevler = new javax.swing.JButton();
        jText = new javax.swing.JTextField();
        jButtontumBitmisGorevler = new javax.swing.JButton();
        jButtontumBitmemisGorevler = new javax.swing.JButton();
        jButtontumCalısanlar = new javax.swing.JButton();
        jButtongorevKimin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButtongorevVermek = new javax.swing.JButton();
        jButtongorevinBirimiNedir = new javax.swing.JButton();
        jButtongorevBaslatmak = new javax.swing.JButton();
        jButtongorevBitirmek = new javax.swing.JButton();
        jButtonsetPersoneller = new javax.swing.JButton();
        jButtonAnaMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jButtonBirimdekiBitmisGorevler.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonBirimdekiBitmisGorevler.setForeground(new java.awt.Color(102, 102, 255));
        jButtonBirimdekiBitmisGorevler.setText("Birimdeki Bitmis Gorevler");
        jButtonBirimdekiBitmisGorevler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBirimdekiBitmisGorevlerActionPerformed(evt);
            }
        });

        jButtonbirimdekiBitmemisGorevler.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonbirimdekiBitmemisGorevler.setForeground(new java.awt.Color(102, 102, 255));
        jButtonbirimdekiBitmemisGorevler.setText("Birimdeki Bitmemis Gorevler");
        jButtonbirimdekiBitmemisGorevler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonbirimdekiBitmemisGorevlerActionPerformed(evt);
            }
        });

        jText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextActionPerformed(evt);
            }
        });

        jButtontumBitmisGorevler.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtontumBitmisGorevler.setForeground(new java.awt.Color(102, 102, 255));
        jButtontumBitmisGorevler.setText("Tum Bitmis Gorevler");
        jButtontumBitmisGorevler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtontumBitmisGorevlerActionPerformed(evt);
            }
        });

        jButtontumBitmemisGorevler.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtontumBitmemisGorevler.setForeground(new java.awt.Color(102, 102, 255));
        jButtontumBitmemisGorevler.setText("Tum Bitmemis Gorevler");
        jButtontumBitmemisGorevler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtontumBitmemisGorevlerActionPerformed(evt);
            }
        });

        jButtontumCalısanlar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtontumCalısanlar.setForeground(new java.awt.Color(102, 102, 255));
        jButtontumCalısanlar.setText("Tum Calısanlar");
        jButtontumCalısanlar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtontumCalısanlarActionPerformed(evt);
            }
        });

        jButtongorevKimin.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtongorevKimin.setForeground(new java.awt.Color(102, 102, 255));
        jButtongorevKimin.setText("Gorev Kimin");
        jButtongorevKimin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtongorevKiminActionPerformed(evt);
            }
        });

        jButtongorevVermek.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtongorevVermek.setForeground(new java.awt.Color(102, 102, 255));
        jButtongorevVermek.setText("Gorev Vermek");
        jButtongorevVermek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtongorevVermekActionPerformed(evt);
            }
        });

        jButtongorevinBirimiNedir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtongorevinBirimiNedir.setForeground(new java.awt.Color(102, 102, 255));
        jButtongorevinBirimiNedir.setText("Gorevin Birimi Nedir");
        jButtongorevinBirimiNedir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtongorevinBirimiNedirActionPerformed(evt);
            }
        });

        jButtongorevBaslatmak.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtongorevBaslatmak.setForeground(new java.awt.Color(102, 102, 255));
        jButtongorevBaslatmak.setText("Gorev Baslatmak");
        jButtongorevBaslatmak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtongorevBaslatmakActionPerformed(evt);
            }
        });

        jButtongorevBitirmek.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtongorevBitirmek.setForeground(new java.awt.Color(102, 102, 255));
        jButtongorevBitirmek.setText("Gorev Bitirmek");
        jButtongorevBitirmek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtongorevBitirmekActionPerformed(evt);
            }
        });

        jButtonsetPersoneller.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonsetPersoneller.setForeground(new java.awt.Color(102, 102, 255));
        jButtonsetPersoneller.setText("Set Personeller");
        jButtonsetPersoneller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsetPersonellerActionPerformed(evt);
            }
        });

        jButtonAnaMenu.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonAnaMenu.setForeground(new java.awt.Color(51, 51, 255));
        jButtonAnaMenu.setText("Çıkış");
        jButtonAnaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnaMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButtongorevVermek, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonBirimdekiBitmisGorevler, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtontumBitmisGorevler, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtontumCalısanlar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtongorevBaslatmak, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonsetPersoneller, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtongorevBitirmek, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtongorevKimin, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonbirimdekiBitmemisGorevler, javax.swing.GroupLayout.PREFERRED_SIZE, 163, Short.MAX_VALUE)
                                    .addComponent(jButtontumBitmemisGorevler, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtongorevinBirimiNedir, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jText, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButtonAnaMenu)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonBirimdekiBitmisGorevler, jButtonbirimdekiBitmemisGorevler, jButtongorevBaslatmak, jButtongorevBitirmek, jButtongorevKimin, jButtongorevVermek, jButtongorevinBirimiNedir, jButtonsetPersoneller, jButtontumBitmemisGorevler, jButtontumBitmisGorevler, jButtontumCalısanlar});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonsetPersoneller, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonBirimdekiBitmisGorevler, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtontumBitmisGorevler, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtongorevKimin, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtontumCalısanlar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtongorevinBirimiNedir, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtongorevVermek, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtongorevBitirmek, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addComponent(jButtongorevBaslatmak, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jText, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonbirimdekiBitmemisGorevler, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtontumBitmemisGorevler, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 183, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jButtonAnaMenu)
                        .addGap(60, 60, 60))))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButtonBirimdekiBitmisGorevler, jButtonbirimdekiBitmemisGorevler, jButtongorevBaslatmak, jButtongorevBitirmek, jButtongorevKimin, jButtongorevVermek, jButtongorevinBirimiNedir, jButtonsetPersoneller, jButtontumBitmemisGorevler, jButtontumBitmisGorevler, jButtontumCalısanlar});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonbirimdekiBitmemisGorevlerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonbirimdekiBitmemisGorevlerActionPerformed
        // TODO add your handling code here:
        if (jText.equals(" ") || jText.equals("")) {
            JOptionPane.showMessageDialog(this, "Lutfen bir birim giriniz !", "Hata", JOptionPane.INFORMATION_MESSAGE);
        } else {
            ArrayList<Gorev> gorevler = new ArrayList<Gorev>();
            Sirket s = new Sirket();
            Birim b = new Birim();
            b.setAdi(new SirketMuduruEkrani().jText.getName());
            for (int i = 0; i < s.birimdekiBitmemisGorevler(b).length; i++) {
                gorevler.add(s.birimdekiBitmemisGorevler(b)[i]);
            }
            for (Gorev gorevler1 : gorevler) {
                DLM.addElement(gorevler1.getGorevAdi());
            }
        }
    }//GEN-LAST:event_jButtonbirimdekiBitmemisGorevlerActionPerformed

    private void jButtontumBitmisGorevlerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtontumBitmisGorevlerActionPerformed
        // TODO add your handling code here:
        ArrayList<Gorev> gorevler = new ArrayList<Gorev>();
        Sirket s = new Sirket();
        for (int i = 0; i < s.tumBitmisGorevler().length; i++) {
            gorevler.add(s.tumBitmisGorevler()[i]);
        }
        for (Gorev gorevler1 : gorevler) {
            DLM.addElement(gorevler1.getGorevAdi());
        }
    }//GEN-LAST:event_jButtontumBitmisGorevlerActionPerformed

    private void jButtongorevinBirimiNedirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtongorevinBirimiNedirActionPerformed
        // TODO add your handling code here:
        if (jText.equals(" ") || jText.equals("")) {
            JOptionPane.showMessageDialog(this, "Lutfen bir gorev giriniz !", "Hata", JOptionPane.INFORMATION_MESSAGE);
        } else {
            Gorev g = new Gorev();
            g.setGorevAdi(new SirketMuduruEkrani().jText.getText());
            ArrayList<Birim> birimler = new ArrayList();
            for (int i = 0; i < g.gorevinBirimiNedir(g).length; i++) {
                birimler.add(g.gorevinBirimiNedir(g)[i]);
            }
            for (Birim birimler1 : birimler) {
                DLM.addElement(birimler1.getAdi());
            }
        }
    }//GEN-LAST:event_jButtongorevinBirimiNedirActionPerformed

    private void jButtongorevVermekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtongorevVermekActionPerformed
        // TODO add your handling code here:
        if (jText.equals(" ") || jText.equals("")) {
            JOptionPane.showMessageDialog(this, "Lutfen bir Personel,Gorev giriniz !", "Hata", JOptionPane.INFORMATION_MESSAGE);
        } else {
            Gorev g = new Gorev();
            g.setGorevAdi(new SirketMuduruEkrani().jText.getText());
            ArrayList<Personel> personel = new ArrayList();
            for (int i = 0; i < g.gorevKimin(g).length; i++) {
                personel.add(g.gorevKimin(g)[i]);
            }
            for (Personel personel1 : personel) {
                g.gorevVermek(g, personel1);
            }
        }

    }//GEN-LAST:event_jButtongorevVermekActionPerformed

    private void jButtontumCalısanlarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtontumCalısanlarActionPerformed
        // TODO add your handling code here:
        Sirket s = new Sirket();
        ArrayList<Personel> personel = new ArrayList();
        for (int i = 0; i < s.tumCalısanlar().length; i++) {
            personel.add(s.tumCalısanlar()[i]);
        }
        for (int i = 0; i < personel.size(); i++) {
            DLM.addElement(personel.get(i).getIsim());
        }
    }//GEN-LAST:event_jButtontumCalısanlarActionPerformed

    private void jButtongorevKiminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtongorevKiminActionPerformed
        // TODO add your handling code here:
        if (jText.equals(" ") || jText.equals("")) {
            JOptionPane.showMessageDialog(this, "Lutfen bir Gorev giriniz !", "Hata", JOptionPane.INFORMATION_MESSAGE);
        } else {
            Personel p = new Personel();
            ArrayList<Personel> personerller = new ArrayList<Personel>();
            Gorev g = new Gorev();
            g.setGorevAdi(new SirketMuduruEkrani().jText.getText());
            for (int i = 0; i < g.gorevKimin(g).length; i++) {
                personerller.add(g.gorevKimin(g)[i]);
            }
            for (Personel personel : personerller) {
                DLM.addElement(personel.getIsim());
            }
        }

    }//GEN-LAST:event_jButtongorevKiminActionPerformed

    private void jButtongorevBitirmekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtongorevBitirmekActionPerformed
        // TODO add your handling code here:
        if (jText.equals(" ") || jText.equals("")) {
            JOptionPane.showMessageDialog(this, "Lutfen bir Gorev giriniz !", "Hata", JOptionPane.INFORMATION_MESSAGE);
        } else {
            Gorev g = new Gorev();
            g.setGorevAdi(new SirketMuduruEkrani().jText.getText());
            g.gorevBitirmek(g);
        }

    }//GEN-LAST:event_jButtongorevBitirmekActionPerformed

    private void jTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextActionPerformed

    private void jButtonBirimdekiBitmisGorevlerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBirimdekiBitmisGorevlerActionPerformed
        // TODO add your handling code here:
        if (jText.equals(" ") || jText.equals("")) {
            JOptionPane.showMessageDialog(this, "Lutfen bir birim giriniz !", "Hata", JOptionPane.INFORMATION_MESSAGE);
        } else {
            ArrayList<Gorev> gorevler = new ArrayList<Gorev>();
            Sirket s = new Sirket();
            Birim b = new Birim();
            b.setAdi(new SirketMuduruEkrani().jText.getName());
            for (int i = 0; i < s.birimdekiBitmisGorevler(b).length; i++) {
                gorevler.add(s.birimdekiBitmisGorevler(b)[i]);
            }
            for (Gorev gorevler1 : gorevler) {
                DLM.addElement(gorevler1.getGorevAdi());
            }
        }

    }//GEN-LAST:event_jButtonBirimdekiBitmisGorevlerActionPerformed

    private void jButtonsetPersonellerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsetPersonellerActionPerformed
        // TODO add your handling code here:
        if (jText.equals(" ") || jText.equals("")) {
            JOptionPane.showMessageDialog(this, "Lutfen bir Personelin isimi/n giriniz !", "Hata", JOptionPane.INFORMATION_MESSAGE);
        } else {
            Personel p = new Personel();
            p.setIsim(new SirketMuduruEkrani().jText.getText());
            p.PersonelinbirimiNedir(p).setPersoneller(p);
        }

    }//GEN-LAST:event_jButtonsetPersonellerActionPerformed

    private void jButtontumBitmemisGorevlerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtontumBitmemisGorevlerActionPerformed
        // TODO add your handling code here:
        ArrayList<Gorev> gorevler = new ArrayList<Gorev>();
        Sirket s = new Sirket();
        for (int i = 0; i < s.tumBitmemisGorevler().length; i++) {
            gorevler.add(s.tumBitmemisGorevler()[i]);
        }
        for (Gorev gorevler1 : gorevler) {
            DLM.addElement(gorevler1.getGorevAdi());
        }
    }//GEN-LAST:event_jButtontumBitmemisGorevlerActionPerformed

    private void jButtongorevBaslatmakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtongorevBaslatmakActionPerformed
        // TODO add your handling code here:
        if (jText.equals(" ") || jText.equals("")) {
            JOptionPane.showMessageDialog(this, "Lutfen bir Gorev giriniz !", "Hata", JOptionPane.INFORMATION_MESSAGE);
        } else {
            Gorev g = new Gorev();
            g.setGorevAdi(new SirketMuduruEkrani().jText.getText());
            g.gorevBaslatmak(g);
        }

    }//GEN-LAST:event_jButtongorevBaslatmakActionPerformed

    private void jButtonAnaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnaMenuActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new anaEkrani().setVisible(true);
    }//GEN-LAST:event_jButtonAnaMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SirketMuduruEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SirketMuduruEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SirketMuduruEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SirketMuduruEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SirketMuduruEkrani().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnaMenu;
    private javax.swing.JButton jButtonBirimdekiBitmisGorevler;
    private javax.swing.JButton jButtonbirimdekiBitmemisGorevler;
    private javax.swing.JButton jButtongorevBaslatmak;
    private javax.swing.JButton jButtongorevBitirmek;
    private javax.swing.JButton jButtongorevKimin;
    private javax.swing.JButton jButtongorevVermek;
    private javax.swing.JButton jButtongorevinBirimiNedir;
    private javax.swing.JButton jButtonsetPersoneller;
    private javax.swing.JButton jButtontumBitmemisGorevler;
    private javax.swing.JButton jButtontumBitmisGorevler;
    private javax.swing.JButton jButtontumCalısanlar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jText;
    // End of variables declaration//GEN-END:variables
}
